/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { FunctionFragment, Result } from "@ethersproject/abi";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  CallOverrides,
  ContractTransaction,
  ethers,
  Overrides,
  PopulatedTransaction,
  Signer,
} from "ethers";
import { TypedEvent, TypedEventFilter, TypedListener } from "./commons";

interface MixedRouteQuoterV2Interface extends ethers.utils.Interface {
  functions: {
    "_quoteExactInputSingleV4(tuple)": FunctionFragment;
    "poolManager()": FunctionFragment;
    "quoteExactInput(bytes,tuple,uint256)": FunctionFragment;
    "quoteExactInputSingleV2(tuple)": FunctionFragment;
    "quoteExactInputSingleV3(tuple)": FunctionFragment;
    "quoteExactInputSingleV4(tuple)": FunctionFragment;
    "uniswapV2Poolfactory()": FunctionFragment;
    "uniswapV3Poolfactory()": FunctionFragment;
    "uniswapV3SwapCallback(int256,int256,bytes)": FunctionFragment;
    "unlockCallback(bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_quoteExactInputSingleV4",
    values: [
      {
        poolKey: {
          currency0: string;
          currency1: string;
          fee: BigNumberish;
          tickSpacing: BigNumberish;
          hooks: string;
        };
        zeroForOne: boolean;
        exactAmount: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
        hookData: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "poolManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quoteExactInput",
    values: [
      BytesLike,
      { nonEncodableData: { hookData: BytesLike }[] },
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteExactInputSingleV2",
    values: [{ tokenIn: string; tokenOut: string; amountIn: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteExactInputSingleV3",
    values: [
      {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteExactInputSingleV4",
    values: [
      {
        poolKey: {
          currency0: string;
          currency1: string;
          fee: BigNumberish;
          tickSpacing: BigNumberish;
          hooks: string;
        };
        zeroForOne: boolean;
        exactAmount: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
        hookData: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV2Poolfactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV3Poolfactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV3SwapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockCallback",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "_quoteExactInputSingleV4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteExactInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteExactInputSingleV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteExactInputSingleV3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteExactInputSingleV4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV2Poolfactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV3Poolfactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV3SwapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockCallback",
    data: BytesLike
  ): Result;

  events: {};
}

export class MixedRouteQuoterV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MixedRouteQuoterV2Interface;

  functions: {
    _quoteExactInputSingleV4(
      params: {
        poolKey: {
          currency0: string;
          currency1: string;
          fee: BigNumberish;
          tickSpacing: BigNumberish;
          hooks: string;
        };
        zeroForOne: boolean;
        exactAmount: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
        hookData: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    poolManager(overrides?: CallOverrides): Promise<[string]>;

    quoteExactInput(
      path: BytesLike,
      param: { nonEncodableData: { hookData: BytesLike }[] },
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    quoteExactInputSingleV2(
      params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>;

    quoteExactInputSingleV3(
      params: {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    quoteExactInputSingleV4(
      params: {
        poolKey: {
          currency0: string;
          currency1: string;
          fee: BigNumberish;
          tickSpacing: BigNumberish;
          hooks: string;
        };
        zeroForOne: boolean;
        exactAmount: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
        hookData: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uniswapV2Poolfactory(overrides?: CallOverrides): Promise<[string]>;

    uniswapV3Poolfactory(overrides?: CallOverrides): Promise<[string]>;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      path: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    unlockCallback(
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  _quoteExactInputSingleV4(
    params: {
      poolKey: {
        currency0: string;
        currency1: string;
        fee: BigNumberish;
        tickSpacing: BigNumberish;
        hooks: string;
      };
      zeroForOne: boolean;
      exactAmount: BigNumberish;
      sqrtPriceLimitX96: BigNumberish;
      hookData: BytesLike;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  poolManager(overrides?: CallOverrides): Promise<string>;

  quoteExactInput(
    path: BytesLike,
    param: { nonEncodableData: { hookData: BytesLike }[] },
    amountIn: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  quoteExactInputSingleV2(
    params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  quoteExactInputSingleV3(
    params: {
      tokenIn: string;
      tokenOut: string;
      amountIn: BigNumberish;
      fee: BigNumberish;
      sqrtPriceLimitX96: BigNumberish;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  quoteExactInputSingleV4(
    params: {
      poolKey: {
        currency0: string;
        currency1: string;
        fee: BigNumberish;
        tickSpacing: BigNumberish;
        hooks: string;
      };
      zeroForOne: boolean;
      exactAmount: BigNumberish;
      sqrtPriceLimitX96: BigNumberish;
      hookData: BytesLike;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uniswapV2Poolfactory(overrides?: CallOverrides): Promise<string>;

  uniswapV3Poolfactory(overrides?: CallOverrides): Promise<string>;

  uniswapV3SwapCallback(
    amount0Delta: BigNumberish,
    amount1Delta: BigNumberish,
    path: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  unlockCallback(
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _quoteExactInputSingleV4(
      params: {
        poolKey: {
          currency0: string;
          currency1: string;
          fee: BigNumberish;
          tickSpacing: BigNumberish;
          hooks: string;
        };
        zeroForOne: boolean;
        exactAmount: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
        hookData: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    poolManager(overrides?: CallOverrides): Promise<string>;

    quoteExactInput(
      path: BytesLike,
      param: { nonEncodableData: { hookData: BytesLike }[] },
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { amountOut: BigNumber; gasEstimate: BigNumber }
    >;

    quoteExactInputSingleV2(
      params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    quoteExactInputSingleV3(
      params: {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { amountOut: BigNumber; gasEstimate: BigNumber }
    >;

    quoteExactInputSingleV4(
      params: {
        poolKey: {
          currency0: string;
          currency1: string;
          fee: BigNumberish;
          tickSpacing: BigNumberish;
          hooks: string;
        };
        zeroForOne: boolean;
        exactAmount: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
        hookData: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { amountOut: BigNumber; gasEstimate: BigNumber }
    >;

    uniswapV2Poolfactory(overrides?: CallOverrides): Promise<string>;

    uniswapV3Poolfactory(overrides?: CallOverrides): Promise<string>;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      path: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    unlockCallback(data: BytesLike, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    _quoteExactInputSingleV4(
      params: {
        poolKey: {
          currency0: string;
          currency1: string;
          fee: BigNumberish;
          tickSpacing: BigNumberish;
          hooks: string;
        };
        zeroForOne: boolean;
        exactAmount: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
        hookData: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    poolManager(overrides?: CallOverrides): Promise<BigNumber>;

    quoteExactInput(
      path: BytesLike,
      param: { nonEncodableData: { hookData: BytesLike }[] },
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    quoteExactInputSingleV2(
      params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    quoteExactInputSingleV3(
      params: {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    quoteExactInputSingleV4(
      params: {
        poolKey: {
          currency0: string;
          currency1: string;
          fee: BigNumberish;
          tickSpacing: BigNumberish;
          hooks: string;
        };
        zeroForOne: boolean;
        exactAmount: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
        hookData: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uniswapV2Poolfactory(overrides?: CallOverrides): Promise<BigNumber>;

    uniswapV3Poolfactory(overrides?: CallOverrides): Promise<BigNumber>;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      path: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unlockCallback(
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _quoteExactInputSingleV4(
      params: {
        poolKey: {
          currency0: string;
          currency1: string;
          fee: BigNumberish;
          tickSpacing: BigNumberish;
          hooks: string;
        };
        zeroForOne: boolean;
        exactAmount: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
        hookData: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    poolManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quoteExactInput(
      path: BytesLike,
      param: { nonEncodableData: { hookData: BytesLike }[] },
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    quoteExactInputSingleV2(
      params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    quoteExactInputSingleV3(
      params: {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    quoteExactInputSingleV4(
      params: {
        poolKey: {
          currency0: string;
          currency1: string;
          fee: BigNumberish;
          tickSpacing: BigNumberish;
          hooks: string;
        };
        zeroForOne: boolean;
        exactAmount: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
        hookData: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uniswapV2Poolfactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uniswapV3Poolfactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      path: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unlockCallback(
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
